export const SHOW_FEED = "SHOW_FEED";
export const FEED_LOADING = "FEED_LOADING";
export const FEED_FAILED = "FEED_FAILED";

export const GET_VIDEO_DETAIL = "GET_VIDEO_DETAIL";
export const GET_VIDEO_DETAIL_LOADING = "GET_VIDEO_DETAIL_LOADING";
export const GET_VIDEO_DETAIL_FAILED = "GET_VIDEO_DETAIL_FAILED";
export const GET_VIDEOS = "GET_VIDEOS";
export const GET_VIDEOS_LOADING = "GET_VIDEOS_LOADING";
export const GET_VIDEOS_FAILED = "GET_VIDEOS_FAILED";

export const GET_CHANNEL_DETAIL = "GET_CHANNEL_DETAIL";
export const GET_CHANNEL_DETAIL_LOADING = "GET_CHANNEL_DETAIL_LOADING";
export const GET_CHANNEL_DETAIL_FAILED = "GET_CHANNEL_DETAIL_FAILED";
export const GET_CHANNEL_VIDEOS = "GET_CHANNEL_VIDEOS";
export const GET_CHANNEL_VIDEOS_LOADING = "GET_CHANNEL_VIDES_LOADING";
export const GET_CHANNEL_VIDEOS_FAILED = "GET_CHANNEL_VIDEOS_FAILED";

export const SEARCH_VIDEOS = "SEARCH_VIDEOS";
export const SEARCH_VIDEOS_LOADING = "SEARCH_VIDEOS_LOADING";
export const SEARCH_VIDEOS_FAILED = "SEARCH_VIDEOS_FAILED";
